accounts/urls.py
from django.urls import path
from .views import login, logout, signup

app_name = 'accounts'
urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('signup/', signup, name='signup'),
]

main/urls.py
# main의 urls.py 작성
from django.urls import path
from django.contrib import admin
from main import views

app_name = 'main'
urlpatterns = [
    path('', views.mainpage, name='mainpage'),
    path('product/<int:product_id>/', views.product_detail, name="product_detail"),
    path('product/<int:product_id>/create_comment/', views.create_comment, name="create_comment"),
    path('delete_comment/<int:comment_id>/', views.delete_comment, name="delete_comment"),
]

project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'), name='main'),
    path('accounts/', include('accounts.urls'), name='accounts'),
]

accounts/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Product(models.Model):
    id                =   models.AutoField(primary_key=True)
    name              =   models.CharField(max_length=50)
    description       =   models.CharField(max_length=50)
    origin_price      =   models.IntegerField()
    discount_price    =   models.IntegerField()
    discount_rate     =   models.IntegerField()
    category          =   models.ManyToManyField('Category')
    notice            =   models.CharField(max_length=200)
    image_url         =   models.URLField(max_length=2000)

    def summary(self):
        return self.description[:20]
    
    def __str__(self):
        return self.name
    
    class Meta:
        db_table    = 'products'

class Category(models.Model):
    name            =   models.CharField(max_length=45)

    def __str__(self):
        return self.name
    class Meta:
        db_table    = 'categories'

class ProductComment(models.Model):
    id              = models.AutoField(primary_key=True)
    user            = models.ForeignKey(User, on_delete=models.CASCADE)
    product         = models.ForeignKey('Product', on_delete=models.CASCADE)
    star            = models.IntegerField()
    content         = models.TextField()
    created_at      = models.DateTimeField(auto_now=True)

    class Meta:
        db_table    = 'product_comments'

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import auth
from django.contrib.auth.models import User

# Create your views here.
def login_page(request):
    return render(request, 'accounts/login.html')


def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect('main:mainpage')
        else:
            return render(request, 'accounts/login.html', {'error': '아이디나 비밀번호가 틀렸습니다. 다시 입력해주세요.'})
    else:
        return render(request, 'accounts/login.html', {'error': '로그인 실패'})
    

def logout(request):
    auth.logout(request)
    return redirect('main:mainpage')

def signup(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        password2 = request.POST['password2']

        # username 미입력시 에러
        if not username:
            return render(request, 'accounts/signup.html', {'error': '닉네임을 입력해주세요.'})
        
        # 비밀번호에 영문 대소문자, 숫자, 특수문자 (@ ! ? - _)가 각각 1개 이상 포함되어야 하며 8자 이상이어야 함
        if not (any(c.isupper() for c in password) and any(c.islower() for c in password) and any(c.isdigit() for c in password) and any(c in '@!?-_' for c in password) and len(password) >= 8):
            return render(request, 'accounts/signup.html', {'error': '비밀번호가 조건에 맞지 않습니다. 다시 입력해주세요.'})

        if password == password2:
            if User.objects.filter(username=username).exists():
                return render(request, 'accounts/signup.html', {'error': '이미 사용중인 닉네임입니다.'})
            else:
                user = User.objects.create_user(username=username, password=password)
                auth.login(request, user)
                return redirect('main:mainpage')
        else:
            return render(request, 'accounts/signup.html', {'error': '비밀번호가 일치하지 않습니다.'})
    else:
        return render(request, 'accounts/signup.html')

main/views.py
from django.shortcuts import render, redirect
from .models import Product, ProductComment

# Create your views here.
# 메인페이지와 메인페이지의 products 정보들을 불러오는 함수
def mainpage(request):
    products = Product.objects.all()
    return render(request, 'main/mainpage.html', {'products': products})

# 상품의 상세페이지를 불러오는 함수
def product_detail(request, product_id):
    product = Product.objects.get(id=product_id)
    comments = product.productcomment_set.all()
    return render(request, 'main/product_detail_page.html', {'product': product, 'comments': comments})

# 상품의 상세페이지에서 댓글을 작성하는 함수
def create_comment(request, product_id):
    product = Product.objects.get(id=product_id)
    if request.method == 'POST':
        star = request.POST['star']
        content = request.POST['content']
        product.productcomment_set.create(star=star, content=content, user_id=request.user.id)
    return redirect('main:product_detail', product_id)

# 상품의 상세페이지에서 댓글을 삭제하는 함수 (단, 댓글 작성자만 삭제 가능)
def delete_comment(request, comment_id):
    comment = ProductComment.objects.get(id=comment_id)
    product = comment.product
    if request.user.id != comment.user_id:
        comments = product.productcomment_set.all()
        return render(request, 'main/product_detail_page.html', {'product': product, 'comments': comments, 'error': '본인의 댓글만 삭제할 수 있습니다.'})
    comment.delete()
    return redirect('main:product_detail', product.id)

accounts/templates/accounts/login.html
<!-- login.html -->
{% extends 'base.html' %} {% load static %}  {% block content %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/accounts/login.css' %}?v=999"
/>
<div class="container_Login"> 
  <div class="titleInputFrame_Login">
    <div class="title_Login">로그인</div>
    <div class="titleInputFrame_Login">
      <div class="inputFrame_Login">
        <form method="POST" action="{%url 'accounts:login' %}" class="inputFrame_Login" id="loginForm_Login">
          {% csrf_token %}
          <input class="idInputBox_Login" id="idInputBox_Login" type="text" name="username" placeholder="아이디를 입력해주세요.">
          <input class="pwInputBox_Login" id="pwInputBox_Login" type="password" name="password" placeholder="비밀번호를 입력해주세요.">
        </form>
      </div>
      <div class="searchFrame_Login">
        <button class="findIdButton_Login">아이디 찾기</button>
        <div class="divideSearchLine_Login">|</div>
        <button class="findPwButton_Login">비밀번호 찾기</button>
      </div>
    </div>
  </div>
<div class="buttonFrame_Login">
    <button class="loginButton_Login" id="loginButton_Login" type="submit" form="loginForm_Login">로그인</button>
    <button class="signupButton_Login" id="signupButton_Login">회원가입</button>
</div>
</div> 
{% endblock %}

{% block scripts %}
<!-- js 파일 -->
<script src="{% static 'js/accounts/login.js' %}"></script>

{% endblock %}

accounts/templates/accounts/signup.html
<!-- 임시 회원가입 페이지 -->
{% extends 'base.html' %} {% block content %}{% load static %}

<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/accounts/signup.css' %}?v=999"
/>
<div class="container">
  <div class="container_Signup">
    <div class="title_Signup">회원가입</div>
    <div class="divideLineTop_Signup"></div>
      <form method="POST" action="{% url 'accounts:signup' %}" class="inputListFrame_Signup" id="signupForm_Signup">
      {% csrf_token %}
    
        <div class="idInputFrame_Signup">
           {% csrf_token %}
          <div class="idInputTitle_Signup">아이디</div>
          <input class="idInputBox_Signup" id="idInputBox_Signup" type="text" name="username" placeholder="아이디를 입력해주세요">
        </div>
    

      <div class="pwInputFrame_Signup">
        <div class="pwInputTitle_Signup">비밀번호</div>
        <div class="pwInputMiniFrame_Signup">
          <input class="pwInputBox_Signup"id="pwInputBox_Signup" type="password" name="password" placeholder="비밀번호를 입력해주세요">
          <div class="pwDescription_Signup" >
            <div>· 비밀번호를 8자 이상으로 작성해주세요. </div>
            <div>· 영문 대소문자, 숫자, 특수문자를 하나 이상 포함해주세요.</div>
            <div>· 사용가능 특수문자  @ ! ? - _</div>
          </div>
        </div>
      </div>
     
        <div class="pwCheckInputFrame_Signup">
          <div class="pwCheckInputTitle_Signup">비밀번호 확인</div>
         <div>
 <input class="pwCheckInputBox_Signup" id="pwCheckInputBox_Signup" type="password" name="password2" placeholder="비밀번호를 한번 더 입력해주세요">
            <small class="pwCheckWarning_Signup">비밀번호가 일치하지 않습니다!</small>
        
         </div>
           
        </div>
   </form>
    
      </div>
      
        

    <div class="divideLineBottom_Signup"></div>
  
  <button disabled class="signupButton_Signup" form="signupForm_Signup" id="signupButton_Signup">가입하기</button>
</div>
{% endblock %}
{% block scripts %}
<!-- js 파일 -->
<script src="{% static 'js/accounts/signup.js' %}"></script>

{% endblock %}

main/templates/main/mainpage.html
{% extends 'base.html' %} {% block content %} {% load static %}
<!-- css 파일 -->
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/main/main_page.css'%}?v=999"
/>
<div class="alignRank">
  <div class="rankBox">
  <a class="menuName" href="#">인기신상랭킹</a>
  <a class="menuName" href="#">입점특가</a>
  <a class="menuName" href="#">간편한끼</a>
  <a class="menuName" href="#">요즘간식</a>

  <a class="menuName" href="#">주방·리빙</a>
  <a class="menuName" href="#">뷰티</a>
  <a class="menuName" href="#">패션·잡화</a> 
</div>
</div>


<div class="frame">
  <div class="leftBox">
    <div class="filterBox">
      <div class="filter1">
        <div class="filter1-1">
          <div>필터</div>
        </div>
        <div class="filter1-2" id="resetBtn">
          <img id="resetIcon" src="{% static 'assets/icons/reset.svg' %}" 
          data-dark-src="{% static 'assets/icons/reset_copy.svg' %}"
          data-origin-src="{% static 'assets/icons/reset.svg' %}"
          alt="restart icon" />
          <div>초기화</div>
        </div>
      </div>
    </div>
  
    <div class="categoryBox">
      <div class="category1">  
        <div>카테고리</div>
        <img src="{% static 'assets/icons/up.svg' %}" alt="up icon" />
      </div>
    </div>

    <div class="category2">
      <div class="category2-1">
        <label class="customCheckbox">
          <input type="checkbox" name="check_group" value="스킨케어·메이크업" />
          <img class="checkImg" src="{% static 'assets/icons/done.svg' %}" alt="done icon" />
        </label>
        <div>스킨케어·메이크업</div>
        <div class="categoryNumber">68</div>
      </div>
      
      <div class="category2-1">
        <label class="customCheckbox">
          <input type="checkbox" name="check_group" value="럭셔리뷰티" />
          <img class="checkImg" src="{% static 'assets/icons/done.svg' %}" alt="done icon" />
        </label>
        <div>럭셔리뷰티</div>
        <div class="categoryNumber">24</div>
     </div>
       
     <div class="category2-1">
      <label class="customCheckbox">
        <input type="checkbox" name="check_group" value="간식·과자·떡" />
        <img class="checkImg" src="{% static 'assets/icons/done.svg' %}" alt="done icon" />
      </label>
        <div>간식·과자·떡</div>
        <div class="categoryNumber">28</div>
      </div>  
    </div>
  </div>
<div class="rightBox">
  <div class="sortingBar">
    <div class="sortingBar1">총 120건</div>
   
    <div class="sortingBar2">
  <div>추천순</div>
  <div class="sortingBarLine"></div>
  <div>신상품순</div>
  <div class="sortingBarLine"></div>
  <div>판매량순</div>
  <div class="sortingBarLine"></div>
  <div>낮은 가격순</div>
  <div class="sortingBarLine"></div>
  <div>높은 가격순</div>
  </div>
 </div>

  <div class="selectedCategories"></div>

  <div class="productFrame">
    {% for product in products %}
    <a href="product/{{product.id}}">
    <div class="productCard3">
      <img class="productCard1" src="{% static 'assets/images/풀무원.jpg' %}" alt="풀무원 사진" />
      <div class="productCard2">
        <img src="{% static 'assets/icons/cart.svg' %}" alt="cart icon" />
        <div>담기</div>
      </div>
      <div class="productCard3-1">샛별배송</div>
      <div class="productCard3-2">{{ product.name }}</div>
      <div class="productCard3-3">{{ product.description }}</div>
      
      <div class="productCardPrice">
          <div class="productCard3-4">{{ product.origin_price }}원</div>
        <div class="productCardSale">
          <div class="productCard3-5">{{ product.discount_rate }}%</div>
          <div class="productCard3-6">{{ product.discount_price }}원</div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
</div>
</a>
<!-- js 파일 -->
<script src="{% static 'js/main/main_page.js'%}"></script>
{% endblock %}

main/templates/main/product_detail_page.html
{% extends 'base.html' %} {% block content %} {% load static %}

<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/main/product_detail_page.css'%}"
/>

<!-- 코드 작성시, 아래 부분(endblock 이전)은 전체 삭제하고 작성하세요 -->

<!----------------tip!---------------->
<!-- 상품 데이터베이스는 프로젝트에 넣어뒀어요 -->
<!-- 아래와 같은 형식으로 사용하세요 -->

<!-- 데이터 사용 예시 
<img src="{{product.image_url}}" style="width: 100px" />
<p>{{product.name}}</p>
<p>{{product.discount_rate}}%</p>
<p>{{product.discount_price}} 원</p>
<p>{{product.notice}}</p>
데이터 사용 예시 -->
<div class="detailpageFrame">
  <div class="productPhoto"></div>
  <div class="detailpageInfoFrame"> 

    <div class="detailpageProductDeliver">샛별배송</div>
    <p class="detailpageProductName">{{product.name}}</p>
    <div class="detailpageProductRatePrice">
      <p class="detailpageProductRate">{{product.discount_rate}}%</p>
      <p class="detailpageProductPrice" data-price="{{product.discount_price}}">{{product.discount_price}} 원</p>
    </div>
    <div class="detailpagedivideLine"></div>
    <div class="detailpageProductNoticeFrame">
      <p class="detailpageProductNoticeTitle">안내사항</p>
      <p class="detailpageProductNotice">{{product.notice}}</p>
    </div>

   
    <div class="detailpagedivideLine"></div>
    
      <div class="detailpageProductSelectFrame">
      <p class="detailpageProductSelectTitle">상품 선택</p>
      <div class="detailpageProductSelectNameFrame">
        <p class="detailpageProductSelectName">{{product.name}}</p>
        <div class="detailpageProductSelectNumberFrame">
          <button class="detailpageProductSelectMinus">-</button>
          <span class="detailpageProductSelectNumber">1</span>
          <button class="detailpageProductSelectPlus">+</button>
        </div>
      </div>
      </div>

      <div class="detailpageBottomFrame">
        <div class="detailpageProductTotalPriceFrame">
          <div class="detailpageProductTotalPriceFrameSmall">
          <p class="detailpageProductTotalPriceTitle">총 상품 금액:</p>
          <span class="detailpageProductTotalPrice" >{{product.discount_price}} 원</span>
        </div>
        </div>
        <div class="detailpageloginButton">로그인</div>
      </div>
    </div>
  </div>
  
</div>

<script src="{% static 'js/main/product_detail_page.js'%}"></script>
{% endblock %}

project/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>컬리 - 마켓컬리/뷰티컬리</title>

    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/base/reset.css'%}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/base/style.css'%}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/base/font.css'%}"
    />
  </head>
  <body>
    <!-- 상단 네브바 -->
    {% include 'shared/_topnav.html' %}
    <!-- 상단 네브바 -->

    <!-- 내용 -->
    {% block content %} {% endblock %}
    <!-- 내용 -->
    {% block scripts %}{% endblock %}

  </body>
</html>

project/templates/shared/_topnav.html
<!--
최상단 네비게이션을 구현한 topnav 입니다.
3개의 section으로 구분되어있습니다.
-->

<!-- 스타일 css import -->
{% load static %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/shared/topnav.css'%}"
/>

<div class="screen">
  <div class="topnav">
    <!-- 로그인 회원가입 고객센터 -->
    <section class="nav-1 text-font2">
      <div class="div">
        <!-- 로그인을 한 경우 -->
        {% if user.is_authenticated %}
        <p class="Caption">{{user.username}}님 안녕하세요!</p>
        <a class="Caption" href="/accounts/logout/">로그아웃</a>

        <!-- 로그인을 하지 않은 경우 -->
        {% else %}
        <a class="Caption" href="/accounts/signup/">회원가입</a>
        <a class="Caption" href="/accounts/login/">로그인</a>
        {% endif %}

        <div class="Caption">고객센터</div>
      </div>
    </section>

    <!-- 로고 서치바 아이콘들 -->
    <div class="search">
      <a class="logo" href="/">
        <img src="{% static 'assets/icons/logo.svg' %}" />
        <div class="B1-bold text-main">마켓컬리</div>
      </a>

      <form class="search-bar">
        <input class="B2" placeholder="검색어를 입력해주세요" />
        <img
          class="icon-24 icon-main"
          src="{% static 'assets/icons/search.svg' %}"
        />
      </form>

      <div class="iconlist">
        <a>
          <img class="icon-24" src="{% static 'assets/icons/location.svg' %}" />
        </a>
        <a>
          <img class="icon-24" src="{% static 'assets/icons/heart.svg' %}" />
        </a>
        <a>
          <img class="icon-24" src="{% static 'assets/icons/cart.svg' %}" />
        </a>
      </div>
    </div>

    <!-- 카테고리들 -->
    <div class="nav-2 text-font1">
      <button class="category">
        <img class="icon-16" src="{% static 'assets/icons/col-3.svg' %}" />
        <div class="Btn-nav">카테고리</div>
      </button>

      <div class="nav-menu-list Btn-nav" id="nav-menu-list">
        <a href="/"> 신상품 </a>
        <a>베스트</a>
        <a>알뜰쇼핑</a>
        <a>특가/혜택</a>
      </div>

      <a class="right-button B2">
        <div class="text-main">샛별·하루</div>
        <div class="text-font3">배송안내</div>
      </a>
    </div>
  </div>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function () {
    const currentPath = window.location.pathname;

    const navMenu = document.getElementById("nav-menu-list");
    const navMenuList = navMenu.children;

    Array.from(navMenuList).forEach(function (menu) {
      if (menu.href == "http://127.0.0.1:8000" + currentPath) {
        menu.style.color = "#5e0080";
      }
    });

    const searchBarInput = document.querySelector(".search-bar > input");
    searchBarInput.addEventListener("keydown", function (event) {
      if (event.key === "Enter") {
        event.preventDefault();
        const searchTerm = searchBarInput.value;
        alert("검색어: " + searchTerm);
      }
    });
  });
</script>